Window {
	BackgroundColor: #000000FF;
	Color: #F7FFF4FF;
}

/* Matches all Labels who are direct children of the table */
/* This is NOT equivalent to "Window Label" */
Window Label {
	FontSize: 24;
	FontName: assets/fonts/Pixel_Square_10.ttf;
}

Button {
	FontSize: 18;
	Color: #ffffffff;
	FontName: assets/fonts/PressStart2P.ttf;
	BackgroundColor: #3797D9FF;
	BorderColor: #3170F0FF;
	Padding: 10;
}
Button:PRELIGHT{
	BackgroundColor: #FFE400FF;
	BorderColor: #FFB50DFF;
	Color: #000000FF;
}